development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: city_watch
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: city_watch
  pool: 5
  username: root
  password:
  host: localhost